apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
    kubernetes.io/ingress.class: shared-nginx
  name: k8s-on-k8s
spec:
  rules:
  - host: k8s.foo.somedomain.edu
    http:
      paths:
      - backend:
          serviceName: apiserver
          servicePort: 443
  tls:
  - hosts:
    - k8s.foo.somedomain.edu
