apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: netshoot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - command:
        - tail
        - -f
        - /dev/null
        image: kubesphere/netshoot:v1.0
        imagePullPolicy: IfNotPresent
        name: netshoot
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
