apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-on-k8s: etcd
      tier: app
  template:
    metadata:
      labels:
        k8s-on-k8s: etcd
        tier: app
    spec:
      hostname: etcd0
      containers:
      - name: etcd
        args:
        - /usr/local/bin/etcd
        - --name=node1
        - --data-dir=/etcd-data
        - --listen-peer-urls=http://0.0.0.0:2380
        - --listen-client-urls=http://0.0.0.0:2379
        - --initial-advertise-peer-urls=http://etcd0:2380
        - --initial-cluster=node1=http://etcd0:2380
        - --advertise-client-urls=http://etcd0:2379
        image: quay.io/coreos/etcd:v3.2.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 2379
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
          - containerPort: 2379
            name: client
            protocol: TCP
          - containerPort: 2380
            name: peer
            protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 2379
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            memory: 250Mi
          requests:
            cpu: 250m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /etcd-data
            name: etcd-data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: etcd-data
        emptyDir: {}
